- name: check kubeadm is install
  shell: dpkg-query -l | grep kubeadm
  register: result
  failed_when: result.rc not in [0, 1]
  
- name: kubeadm reset
  shell:  yes 'y' |kubeadm reset && ip link delete cni0 && ip link delete flannel.1
  when: result.rc == 0
  ignore_errors: yes

- name: kubeadm init
  command: kubeadm init --apiserver-advertise-address={{inventory_hostname}} --pod-network-cidr=10.244.0.0/16
- name: get env
  command: echo {{ item }}
  with_list:
    - $HOME
    - $(id -u)
    - $(id -g)
  register: env
- name: mkdir direcrory
  shell: mkdir -p {{ env.results.0.stdout  }}/.kube
- name: kubeadm set config 
  shell: cp /etc/kubernetes/admin.conf {{   env.results.0.stdout   }}/.kube/config && chown {{   env.results.1.stdout  }}:{{  env.results.2.stdout   }} {{  env.results.0.stdout   }}/.kube/config
- name: download flannel
  get_url:
    url:  https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: /tmp/kube-flannel.yml
    force: true
- name: apply flannel
  shell: kubectl apply -f /tmp/kube-flannel.yml
- name: kubeadm token create
  shell: kubeadm token create --print-join-command
  register: kubeadm_token