- name: init
  command: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove
- name: add k8s key
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
- name: apt
  apt:
      name: "{{ packages }}"
  vars:
    packages:
      - kubeadm
      - kubelet
      - kubectl
    state: present

- name: start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
