- name: check kubeadm setuped
  shell: ip link | grep flannel.1
  register: setuped
  failed_when: setuped.rc not in [0, 1]
 
- name: kubeadm reset
  shell: yes 'y' | kubeadm reset && ip link delete flannel.1
  when: setuped.rc == 0

- name: kubeadm set token
  shell: "{{ hostvars[groups[\"master\"][0]][\"kubeadm_token\"][\"stdout\"] }}"